### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/mapa-mental-web-3-Band-hi#1]
![Mapa Mental Web 3 0](https://user-images.githubusercontent.com/46431649/160495227-0f13da9d-9180-4b54-90e3-5ea7f9200dcc.png)

**Comment by christopheremv** [comment]
calificación :19 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
